onEvent('recipes', event => {
  event.remove({id: 'extradisks:disk/shaped/infinite_storage_disk'})
  event.remove({id: 'extradisks:disk/shapeless/infinite_storage_disk'})
  event.remove({id: 'extradisks:disk/shaped/infinite_fluid_disk'})
  event.remove({id: 'extradisks:disk/shapeless/infinite_fluid_disk'})
  event.remove({id: 'extradisks:part/infinite_storage_part'})
  event.remove({id: 'extradisks:part/infinite_fluid_part'})
  event.remove({id: 'extradisks:block/infinite_fluid_block'})
  event.remove({id: 'extradisks:block/infinite_fluid_block'})
  event.remove({type: 'mysticalagriculture:infusion'})
})