StartupEvents.registry('item', event => {
	event.create('mk1circuit').displayName('MK1 Circuit')
	event.create('mk2circuit').displayName('MK2 Circuit')
	event.create('mk3circuit').displayName('MK3 Circuit')
	event.create('mk4circuit').displayName('MK4 Circuit')
	event.create('mk5circuit').displayName('MK5 Circuit')
	event.create('incomplete_certus_wrench').displayName('Incomplete Certus Wrench')
	event.create('incomplete_quartz_wrench').displayName('Incomplete Quartz Wrench')
	event.create('incomplete_basic_processor').displayName('Incomplete Raw Basic Processor')
	event.create('incomplete_improved_processor').displayName('Incomplete Raw Improved Processor')
	event.create('incomplete_advanced_processor').displayName('Incomplete Raw Advanced Processor')
	event.create('leaded_iron_compound').displayName('Leaded Iron Compound')
	event.create('leaded_iron').displayName('Leaded Iron')
})
	StartupEvents.registry('fluid', event =>{
		event.create('blitz_blood')
    .thickTexture(0xE2E3C5)
    .bucketColor(0xE2E3C5)
    .displayName('Blitz Blood'),
	event.create('liquifacted_graphite')
    .thickTexture(0x373737)
    .bucketColor(0x373737)
    .displayName('Liquifacted Graphite')
})