onEvent('recipes', event => {
  event.remove({id: 'extradisks:disk/shaped/infinite_storage_disk'})
  event.remove({id: 'extradisks:disk/shapeless/infinite_storage_disk'})
  event.remove({id: 'extradisks:disk/shaped/infinite_fluid_disk'})
  event.remove({id: 'extradisks:disk/shapeless/infinite_fluid_disk'})
  event.remove({id: 'extradisks:part/infinite_storage_part'})
  event.remove({id: 'extradisks:part/infinite_fluid_part'})
  event.remove({id: 'extradisks:block/infinite_fluid_block'})
  event.remove({id: 'extradisks:block/infinite_fluid_block'})
  event.remove({type: 'mysticalagriculture:infusion'})
  event.remove({id: 'ftbic:macerating/generated/dust_from_gem/emendatusenigmatica/certus_quartz_dust'})
event.remove({id: 'appliedenergistics2:inscriber/silicon_print'})
event.remove({id: 'appliedenergistics2:network/blocks/inscribers'})
})